# Generated by Django 5.0.2 on 2024-02-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lesson_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_id',
        ),
    ]
