# Generated by Django 5.0.4 on 2024-05-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='created_at',
        ),
    ]
