# Generated by Django 5.1.3 on 2024-12-09 09:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='article',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/2.png', upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='media/lessons/figma1.jpg', upload_to='lessons/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default='articles/2.png'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
