# Generated by Django 5.1.3 on 2024-12-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_lesson_article_remove_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='media/articles/2.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/articles/2.png', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='media/lessons/figma1', upload_to='lessons/'),
        ),
    ]
