# Generated by Django 5.1.3 on 2024-12-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_article_created_at_article_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='Default subtitle', max_length=200),
        ),
    ]
