# Generated by Django 5.1.3 on 2024-12-09 10:09

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=main.models.get_default_image, upload_to='articles/'),
        ),
    ]
